version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Configuring linux environment
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing tools
          command: 'apt-get update && apt-get install -y build-essential gcc-avr binutils-avr avr-libc'
      - run:
          name: Building project
          command: 'make'